### ISSUE TITLE
建议支持TypeScript

### ISSUE THREAD

**Issue by mishengqiang** [AlloyTeam/omi#13]
请问有计划支持TypeScript语言吗？

虽然ES6的使用解决了很多问题，但是随着组件化和模块化的前端开发模式，以及业务量的增大，ES6急需增强以便辅助开发者专心开发业务，TypeScript就是为此而生的。

TypeScript可以为JS添加类型和智能分析，可以帮助开发者构建大型的、强壮的软件。
TypeScript也不会为开发者增加很大的学习成本，TS≈Type+ES。
现在三大流行前端库或者框架（React、Vue和Angular 2）都可以使用TypeScript来编码。

**Comment by dntzhang** [comment]
啊~~    规划中... 多谢建议。

**Comment by dntzhang** [comment]
@pasturn 正在搞~~  ，你可以先体验下 https://github.com/AlloyTeam/omi/tree/master/ts
@mishengqiang

**Comment by dntzhang** [comment]
已经支持~~
