### ISSUE TITLE
textarea 问题等

### ISSUE THREAD

**Issue by cloudcome** [AlloyTeam/omi#14]
- html 模板里有 textarea，而 textarea 是可以被拖拽的，导致在数据更新之后，textarea 又被重置为初始状态
- 点击 add 之后，textarea 没有清空，再次点击，新建了一个空的 todo
- 内联事件？

[playground](http://alloyteam.github.io/omi/example/playground/index.html?code=class%20List%20extends%20Omi.Component%20%7B%0A%20%20%20%20constructor(data)%20%7B%0A%20%20%20%20%20%20%20%20super(data)%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20render%20()%20%7B%0A%20%20%20%20%20%20%20%20return%20%60%3Cul%3E%20%7B%7B%23items%7D%7D%20%3Cli%3E%7B%7B.%7D%7D%3C%2Fli%3E%20%7B%7B%2Fitems%7D%7D%3C%2Ful%3E%60%3B%0A%20%20%20%20%7D%0A%7D%0A%0AOmi.makeHTML(%27List%27%2C%20List)%3B%0A%0Aclass%20Todo%20extends%20Omi.Component%20%7B%0A%20%20%20%20constructor(data)%20%7B%0A%20%20%20%20%20%20%20%20super(data)%3B%0A%20%20%20%20%20%20%20%20this.data.length%20%3D%20this.data.items.length%3B%0A%20%20%20%20%20%20%20%20this.childrenData%20%3D%20%5B%20%7B%20items%20%3A%20this.data.items%20%7D%20%5D%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20add%20(evt)%20%7B%0A%20%20%20%20%20%20%20%20evt.preventDefault()%3B%0A%20%20%20%20%20%20%20%20this.list.data.items.push(this.data.text)%3B%0A%20%20%20%20%20%20%20%20this.data.length%20%3D%20this.list.data.items.length%3B%0A%20%20%20%20%20%20%20%20this.data.text%20%3D%20%27%27%3B%0A%20%20%20%20%20%20%20%20this.update()%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20style%20()%20%7B%0A%20%20%20%20%20%20%20%20return%20%60%0A%20%20%20%20%20%20%20%20h3%20%7B%20color%3Ared%3B%20%7D%0A%20%20%20%20%20%20%20%20button%7B%20color%3Agreen%3B%7D%60%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20handleChange(target)%7B%0A%20%20%20%20%20%20%20%20this.data.text%20%3D%20target.value%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20render%20()%20%7B%0A%20%20%20%20%20%20%20%20return%20%60%0A%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%20%20%3Ch3%3ETODO%3C%2Fh3%3E%0A%20%20%20%20%20%20%20%20%20%20%3CList%20name%3D%22list%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cform%20onsubmit%3D%22add(event)%22%20%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctextarea%20type%3D%22text%22%20onchange%3D%22handleChange(this)%22%20placeholder%3D%22todo%22%3E%7B%7Btext%7D%7D%3C%2Ftextarea%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cbutton%3EAdd%20%23%7B%7Blength%7D%7D%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%20%20%3C%2Fform%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%60%3B%0A%20%20%20%20%7D%0A%7D%0A%0A%0AOmi.render(new%20Todo(%7B%20items%3A%20%5B%27Omi%27%2C%27dntzhang%27%2C%27AlloyTeam%27%5D%20%2C%20text%20%3A%20%27%27%20%7D)%2C%27%23container%27)%3B)

**Comment by dntzhang** [comment]
收到。尽快给你答复

**Comment by dntzhang** [comment]
@cloudcome 
在omi0.2.1版本已经修复了这个问题。但是使用姿势有些变化：
```html
  <textarea type="text" onchange="handleChange(this)" value='{{text}}' placeholder="todo"></textarea>
```
[playground](http://alloyteam.github.io/omi/example/playground/index.html?code=class%20List%20extends%20Omi.Component%20%7B%0A%20%20%20%20constructor(data)%20%7B%0A%20%20%20%20%20%20%20%20super(data)%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20render%20()%20%7B%0A%20%20%20%20%20%20%20%20return%20%60%3Cul%3E%20%7B%7B%23items%7D%7D%20%3Cli%3E%7B%7B.%7D%7D%3C%2Fli%3E%20%7B%7B%2Fitems%7D%7D%3C%2Ful%3E%60%3B%0A%20%20%20%20%7D%0A%7D%0A%0AOmi.makeHTML(%27List%27%2C%20List)%3B%0A%0Aclass%20Todo%20extends%20Omi.Component%20%7B%0A%20%20%20%20constructor(data)%20%7B%0A%20%20%20%20%20%20%20%20super(data)%3B%0A%20%20%20%20%20%20%20%20this.data.length%20%3D%20this.data.items.length%3B%0A%20%20%20%20%20%20%20%20this.childrenData%20%3D%20%5B%20%7B%20items%20%3A%20this.data.items%20%7D%20%5D%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20add%20(evt)%20%7B%0A%20%20%20%20%20%20%20%20evt.preventDefault()%3B%0A%20%20%20%20%20%20%20%20this.list.data.items.push(this.data.text)%3B%0A%20%20%20%20%20%20%20%20this.data.length%20%3D%20this.list.data.items.length%3B%0A%20%20%20%20%20%20%20%20this.data.text%20%3D%20%27%27%3B%0A%20%20%20%20%20%20%20%20this.update()%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20style%20()%20%7B%0A%20%20%20%20%20%20%20%20return%20%60%0A%20%20%20%20%20%20%20%20h3%20%7B%20color%3Ared%3B%20%7D%0A%20%20%20%20%20%20%20%20button%7B%20color%3Agreen%3B%7D%60%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20handleChange(target)%7B%0A%20%20%20%20%20%20%20%20this.data.text%20%3D%20target.value%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20render%20()%20%7B%0A%20%20%20%20%20%20%20%20return%20%60%0A%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%20%20%3Ch3%3ETODO%3C%2Fh3%3E%0A%20%20%20%20%20%20%20%20%20%20%3CList%20name%3D%22list%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cform%20onsubmit%3D%22add(event)%22%20%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctextarea%20type%3D%22text%22%20onchange%3D%22handleChange(this)%22%20value%3D%27%7B%7Btext%7D%7D%27%20placeholder%3D%22todo%22%3E%3C%2Ftextarea%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cbutton%3EAdd%20%23%7B%7Blength%7D%7D%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%20%20%3C%2Fform%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%60%3B%0A%20%20%20%20%7D%0A%7D%0A%0A%0AOmi.render(new%20Todo(%7B%20items%3A%20%5B%27Omi%27%2C%27dntzhang%27%2C%27AlloyTeam%27%5D%20%2C%20text%20%3A%20%27%27%20%7D)%2C%27%23container%27)%3B)
