### ISSUE TITLE
使用 Jekyll 或 Hexo 写文档？

### ISSUE THREAD

**Issue by xcatliu** [AlloyTeam/omi#16]
只是一个提议，感觉 Jekyll 或 Hexo 更适合做这种静态的文档网站。

React 是在主项目中使用 Jekyll 生成文档。
Vue 是另开了一个项目，使用的 Hexo。

**Comment by dntzhang** [comment]
如果生成出来的站能比 http://alloyteam.github.io/omi/website/docs.html 这个体验好，可以换啊。
现在的流程是
1：写 markdown，
2 ：然后npm run website，然后提交就会生成好website/docs.html

**Comment by dntzhang** [comment]
@xcatliu 
刚改了下配置的相应代码，npm run website 搞出来一版了。http://alloyteam.github.io/omi/website/docs_en.html

**Comment by xcatliu** [comment]
不错呀，先就用这套 docs 吧。优先完善核心功能和修复 bugs，将来有精力了再优化网站体验。
