### ISSUE TITLE
omi-id, name, refs 是重复的 api 吗？

### ISSUE THREAD

**Issue by xcatliu** [AlloyTeam/omi#17]
貌似这三者是一样的作用？

**Comment by dntzhang** [comment]
omi-id是标记全局id。任何组件下都能通过 Omi.get拿到
name是名字，当前组件通过this拿到
ref是标记dom，当前组件通过this.refs拿到

**Comment by xcatliu** [comment]
name 只有当用在 custom component 上的时候才能通过 this 拿到吗？
为什么不把 name 和 refs 统一为 refs 呢？

**Comment by dntzhang** [comment]
是的，name只是那自定义组件对象的实例。
refs是拿dom element

**Comment by dntzhang** [comment]
不是同一类东西，所以没有统一到refs

**Comment by xcatliu** [comment]
懂了，感谢答疑🙏
