### ISSUE TITLE
scope css在伪元素的实现上bug

### ISSUE THREAD

**Issue by Uheinanba** [AlloyTeam/omi#25]
![gpv b t i4 4ruk zses7](https://cloud.githubusercontent.com/assets/7878971/24180983/16f1dadc-0ef3-11e7-8d2c-f6b769da0615.png)
如图所示。label:before[omi_scoped_1] ,omi_scoped_1作用在 before后面选择器失效了

**Comment by xcatliu** [comment]
Thanks! Working on it.
