### ISSUE TITLE
请教自定义标签

### ISSUE THREAD

**Issue by vipx** [AlloyTeam/omi#27]
假设有三个自定义标签A,B,C，使用结构如下：
`
<A>
  <B>
    <C>...</C>
    <A>...</A>
    <A>...</A>
  </B>
</A>
`
我想将A标签包含的内容全部渲染到A中，B包含的内容渲染到B中，不知道我应该怎样解决
这个问题的难点在于三个标签可以互相包含，如果通过传入data，那样代码的可读性就太差了

**Comment by dntzhang** [comment]
omi没有slot，以后估计也不会有，但是nest self还是支持的。所以你这个应该是拆成两个组件的。
A组件：
```js
<A> 
    <B> </B> 
</A>
```

B组件：
```js
<div>
    <C>...</C> 
    <A>...</A> 
    <A>...</A>
</div>
```

**Comment by vipx** [comment]
我是在尝试编写布局组件时遇到了这个问题，如row、col、panel，row中包含col，col可以包含panel，panel中可以再包含row、col，毕竟它们是需要闭合标签的，不过既然没计划支持slot，那我只能尝试其他的解决方案了，感谢您的答复
