### ISSUE TITLE
omi 没有配套的router吗？

### ISSUE THREAD

**Issue by louisscrew** [AlloyTeam/omi#28]
没有配套的router吗？

**Comment by dntzhang** [comment]
哈哈。这个马上就有 ~~   0.1.0即将到来~~  https://github.com/AlloyTeam/omi/tree/master/plugins/omi-router

**Comment by dntzhang** [comment]
@louisscrew  omi-router v0.1.0 已发布。可以试试~~~

**Comment by louisscrew** [comment]
好。我试试

**Comment by louisscrew** [comment]
@dntzhang router目前只支持hash模式是吗？

**Comment by dntzhang** [comment]
@louisscrew  是的:)
