### ISSUE TITLE
 为什么不用自家的js模板呢？

### ISSUE THREAD

**Issue by taolive** [AlloyTeam/Omi#3]
为什么不用自家的 js 模板呢（!art-template - Template Engine | http://aui.github.com/artTemplate/）？ 自家的框架，不用自家的模板，真是搞不懂。。真是没事做。。看来腾讯集团部门之间。。。。

**Comment by kmdjs** [comment]
@taolive 

mustachejs是非常通用的模板引擎，各个语言都有，但目前确实拖了性能的后腿。
自家的模板引擎是这个 https://github.com/AlloyTeam/SodaRender 。

artTemplate性能非常不错，是前腾讯员工的作品。关于模板，很容易切换，因为Nuclear没有与模板做很紧密的耦合。等我试试 Nuclear 使用artTemplate渲染的性能如何。

**Comment by kmdjs** [comment]
@taolive

已支持artTemplate或者任何模板引擎
