### ISSUE TITLE
ie8 怎么兼容？

### ISSUE THREAD

**Issue by louisscrew** [AlloyTeam/omi#31]
我已经在index页面上引入了es5-shim.js

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Omi</title>
    <script src="js/es5-shim.min.js"></script>
    <link rel="stylesheet" href="css/index-ef14a72eca.css">
</head>
<body>

    <script src="js/vendor.9da31384.js"></script>

    <script src="js/omi.27cdf71e.js"></script>

    <script src="js/index.25f7b79d.js"></script>

</body>
</html>
```

但是在运行的时候还是出现了错误。

错误如下：
网页错误详细信息

用户代理: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.2)
时间戳: Thu, 30 Mar 2017 07:39:28 UTC

消息: 对象不支持此操作
行: 1059
字符: 2
代码: 0
URI: file:///D:/screwspace/webfront/omi/test/dist/js/omi.27cdf71e.js

消息: 对象不支持此属性或方法
行: 1
字符: 1
代码: 0
URI: file:///D:/screwspace/webfront/omi/test/dist/js/omi.27cdf71e.js

消息: 缺少标识符、字符串或数字
行: 16
字符: 79
代码: 0
URI: file:///D:/screwspace/webfront/omi/test/dist/js/index.25f7b79d.js

应该还是兼容性的问题。

**Comment by dntzhang** [comment]
webpack config里加上

```js
  //support ie8
                    plugins : [
                        "transform-es3-property-literals",
                        "transform-es3-member-expression-literals"
                    ]
```

**Comment by louisscrew** [comment]
我已经添加了上面的配置和es5-sham。。。

结果
![Uploading image.png…]()

**Comment by dntzhang** [comment]
重新build下项目

**Comment by dntzhang** [comment]
你把我发的cdn另存为

**Comment by louisscrew** [comment]
我肯定是重新运行的npm run dist呀

公司的网络禁止这个cdn了。。还没有别的cdn吗？或者给我发个邮件？wen-q@neusoft.com

**Comment by dntzhang** [comment]
Npm Run dev试试，看下什么错

**Comment by louisscrew** [comment]
用Npm Run dev也一样，在IE8下面也看不出来什么错呀。
就是如下错误

消息: 对象不支持此属性或方法
行: 1
字符: 239
代码: 0
URI: http://localhost:3000/js/es5-sham.js

**Comment by dntzhang** [comment]
怎么会看不出来什么错啊 =  =！ 你全部都不要用压缩版的js就能看出来什么错了~~

**Comment by louisscrew** [comment]
我的天。。IE8呀。老兄。我还真不知道用什么能查看到错误。

首先第一个错误点就是es5-sham.js报出来的，提示对象不支持此属性或方法，下一个错误就是
vendor.js报出来的。定位的是
Object.defineProperty方法不支持。


所以错误很明显，es5-sham根本没有起作用。

**Comment by dntzhang** [comment]
是的，所以说这个看上去是你的es5-sham.js不兼容ie8.  压根就没起作用

**Comment by dntzhang** [comment]
//s.url.cn/qqun/xiaoqu/buluo/p/js/es5-sham-es5-sham.min.77c4325f.js

**Comment by dntzhang** [comment]
http://s.url.cn/qqun/xiaoqu/buluo/p/js/es5-sham-es5-sham.min.77c4325f.js

**Comment by louisscrew** [comment]
好使了。
我在es5-shim 的github上下载到为压缩的源码。

之后放到了js目录。

并且在webpack上把两个源码压缩到了vendor.js里面。运行就成功了。不止需要sham还需要shim

我的配置如下：
config.entry.vendor = [
        './src/js/es5-shim.js'
        ,'./src/js/es5-sham.js'
        ,'omi'
        ,'./src/common/class_list.js'
    ];
    config.output.filename = '[name].js';
    config.plugins[1] = new commonChunkPlugin({
        name:"vendor",
        filename:"vendor.js"
    })

这样在IE8下就正常的运行。 谢谢。

**Comment by Muna-Lombe** [comment]
Received with thanks.
