### ISSUE TITLE
md2site—预览或生成网站报错

### ISSUE THREAD

**Issue by wupengju** [AlloyTeam/omi#35]
js目录添加的vendor.js中没有Omi全局对象上也没有useStore方法
```
// docs_main_cn.js
import Omi from 'omi';
import Frame from '../component/frame.js';
import AppStore from './app-store.js'

var store = new AppStore({lan:'cn'})
Omi.useStore(store,true);

Omi.render(new Frame(),'body',true);
```

浏览器控制台报错：
```
docs-cn.js:22 Uncaught TypeError: _omi2.default.useStore is not a function
```

Omi的测试项目的vendor.js【132KB】和md2site的vendor.js【177KB】不一样，没懂为什么
AppStore继承Omi.Store且添加了实例方法来将Markdown进行转化，应该不会增加md2site的vendor.js的文件体积.

**Comment by dntzhang** [comment]
多谢~  我们看看~~

**Comment by xcatliu** [comment]
应该就是 omi 版本更新后，template/app 里面的内容没有更新。
template/app 使用的是 latest 的 omi，omi 有了不兼容的更新，所以就出错了。

应该将 template/app 同步 docs 里面的内容？

**Comment by dntzhang** [comment]
@wupengju 
安装最新的md2site。已经修复了~~
