### ISSUE TITLE
提几点小小的建议

### ISSUE THREAD

**Issue by OuYancey** [AlloyTeam/omi#44]
1. 是否可以将中英文文档分离；
2. 应该要增加**AlloyTeam**的`Eslint`风格检查(代码风格实在有点飘逸。。。)；
3. 是否可以将 plugins 从项目中分离？
4. 项目结构是否可以整理一下？。。。
5. PR Welcome?

**Comment by dntzhang** [comment]
欢迎PR~~

**Comment by OuYancey** [comment]
是否可以增加代码的lint功能？不然实在有点担心自己的风格是否能达到要求。。。

**Comment by dntzhang** [comment]
你直接pr过来就是，我们会review啊。相信自己:)

**Comment by OuYancey** [comment]
其实我在找关于[Alloyteam代码规范](https://github.com/AlloyTeam/CodeGuide)的eslint-config。我先找找。

**Comment by dntzhang** [comment]
好，等你pr~~
