### ISSUE TITLE
看上去跟Vue很像，但是为什么Vue火了起来，而omi没有

### ISSUE THREAD

**Issue by SteveCruise** [AlloyTeam/omi#48]
腾讯开源的东西不多啊，有种闷声发大财的感觉。

**Comment by zhaomenghuan** [comment]
出发点不同，Vue 更 Open，在设计上相对也更加成熟。

**Comment by SteveCruise** [comment]
好吧，理想是美好的，但是一个的项目发展下来如果变得尴尬了，能内部跳槽到其它部门不？

**Comment by dntzhang** [comment]
@SteveCruise 有啥尴尬的？你想多了吧~~ :)

**Comment by OuYancey** [comment]
挺好奇alloy内部哪些项目用到了omi？

**Comment by SteveCruise** [comment]
我知道大厂员工有意志有魄力，争世界第一有失利也非常正常，如果成了搜搜、腾讯微博，不如果断砍掉，节约下来一批优秀的工程师去做更有益的事情。

**Comment by dntzhang** [comment]
@OuYancey 
蛮多的。 最近我们内部同事写的文章 https://github.com/AlloyTeam/omi/blob/master/tutorial/omi-qq-story.md

**Comment by dntzhang** [comment]
@SteveCruise 说得不错，但是现在说失利还为时过早，omi才刚刚推出来多久啊~~~
