### ISSUE TITLE
如果组件过多，浏览器重排重绘会不会造成渲染速度慢的问题？有做过这方面的测试么？

### ISSUE THREAD

**Issue by yalishizhude** [AlloyTeam/Omi#5]

**Comment by kmdjs** [comment]
http://alloyteam.github.io/Nuclear/pt/

**Comment by kmdjs** [comment]
@yalishizhude   http://alloyteam.github.io/Nuclear/pt/

**Comment by kmdjs** [comment]
@yalishizhude
目前来说，虚拟dom更快是不用争论的，有得必有失，如框架体积，编程体验等等。但是基于html的组件化应用编程和游戏编程不一样，帧率不用60fps。低帧率按需更新用户根本不会觉得卡顿。

**Comment by yalishizhude** [comment]
@kmdjs 看不懂什么意思，能配个说明不？

**Comment by kmdjs** [comment]
但是基于html的组件化应用编程和游戏编程不一样，帧率不用60fps。低帧率按需更新用户根本不会觉得卡顿。对了，忘了说了。切断observejs双向绑定性能可以翻倍,超大的list可以考虑不用双向绑定。比如最新的测试：http://alloyteam.github.io/Nuclear/pt/  @yalishizhude
