### ISSUE TITLE
website 和 todomvc 的用途？

### ISSUE THREAD

**Issue by OuYancey** [AlloyTeam/omi#50]
`docs/`, `tutorial/`, `website/`, `todomvc/`, `md2site/` 这几个目录感觉功能重复，对新人不友好。
不知道可否整理一下？感觉眼花缭乱的。。。

**Comment by dntzhang** [comment]
好，这个我来搞~

**Comment by OuYancey** [comment]
`website`是在哪里进入的？我怎么没找到入口。。。

**Comment by OuYancey** [comment]
https://alloyteam.github.io/omi/
里面没找到`website/`里的东西

**Comment by dntzhang** [comment]
当然有啊，比如 https://alloyteam.github.io/omi/website/index-en.html

**Comment by OuYancey** [comment]
是不是可以把bak删掉，毕竟git还是能找回的。
然后把网站相关的东西放入docs。
我刚刚看了下[github文档](https://help.github.com/articles/user-organization-and-project-pages/)，好像能自动找 master 下的`docs/`

**Comment by dntzhang** [comment]
website先不动。docs里面就放一个readme~~  bak先留着，我等来清理~

**Comment by dntzhang** [comment]
你qq多少？加下qq

**Comment by OuYancey** [comment]
公司卡了QQ的网，弄了下代理才登上。加好了
