### ISSUE TITLE
select在调用this.update()后异常

### ISSUE THREAD

**Issue by clll7** [AlloyTeam/omi#53]
![image](https://user-images.githubusercontent.com/6949822/30587745-d57a00ea-9d66-11e7-9703-898ff3cf4a1e.png)
![image](https://user-images.githubusercontent.com/6949822/30588035-c6d054b2-9d67-11e7-9a6a-69ae6cec0048.png)

调用this.update()后，data有值，但select元素变为空值。浏览器：UC、chrome。

代码：
![image](https://user-images.githubusercontent.com/6949822/30587843-2d21576c-9d67-11e7-9826-45b7f5b88571.png)
![image](https://user-images.githubusercontent.com/6949822/30587857-352ea9d2-9d67-11e7-9f0e-8d2dd8faa774.png)
![image](https://user-images.githubusercontent.com/6949822/30587875-4204afa8-9d67-11e7-9331-bc64770696d0.png)

**Comment by clll7** [comment]
目前使用了在update之后，使用操作dom的方法赋值，暂时可以解决

![image](https://user-images.githubusercontent.com/6949822/30592837-fa3569e2-9d7a-11e7-891c-214ebf45dba5.png)
![image](https://user-images.githubusercontent.com/6949822/30592872-291f4958-9d7b-11e7-8506-ead01086492d.png)

**Comment by dntzhang** [comment]
看看这里。要给value就可以了
https://github.com/AlloyTeam/omi/blob/master/tutorial/all.md#select标签

**Comment by clll7** [comment]
复制官方示例代码运行也有这个问题，调用update方法后输入控件的值变为空值。ps:用omi-cli构建的项目。

![image](https://user-images.githubusercontent.com/6949822/30625660-167bacb6-9df7-11e7-8b5a-df7a38151e17.png)

**Comment by dntzhang** [comment]
多谢反馈。但是我试了 http://alloyteam.github.io/omi/website/redirect.html?type=form 这里是没有问题的。你更新到最新的cli~~

**Comment by clll7** [comment]
好的，感谢
