### ISSUE TITLE
请问使用omi如何制作一些动画效果

### ISSUE THREAD

**Issue by YangDaniu** [AlloyTeam/omi#54]
目前能想到的办法就是不断地update相关的值，性能感觉不是特别好

**Comment by dntzhang** [comment]
直接运动就ok了！update的时候同步一下运动结果的状态，哪里会去不断update相关值？
https://github.com/AlloyTeam/omi/tree/master/plugins/omi-transform

**Comment by dntzhang** [comment]
https://github.com/AlloyTeam/omi/blob/master/tutorial/omi-transform.md

**Comment by YangDaniu** [comment]
就比如我要做一个淡入淡出的效果，这个效果和滚动距离顶部的距离有关系，我的做法是
<div style="opacity:{{scrollTop}}"></div>这样我需要不断调用Omi.instance.update，这种做法是否合理？是否会导致其他数据的diff而带来一些性能问题呢？因为移动端动画性能还是比较重要的
我使用iscoll的scroll事件进行更新在快速移动时感觉有一些闪屏的情况

**Comment by dntzhang** [comment]
直接操作dom！直接操作dom！直接操作dom！运动完成再同步一个状态给组件的data就可以了。
