### ISSUE TITLE
如何实现sticky footer

### ISSUE THREAD

**Issue by clll7** [AlloyTeam/Omi#6]
因为render会给模板套一层div，所以无法传递html和body的height:100%了

**Comment by kmdjs** [comment]
@clll7 
当初这样设计的目地是为了
1:支持局部CSS
2:不用强制用户闭合html
目前你可以在onRefresh给this.node加class解决：
```js
    onRefresh:function(){
        this.node.classList.add("aa")
    },
```

**Comment by clll7** [comment]
好的，明白了，感谢
